services:
  fastapi:
    build: ./fastapi
    network_mode: "host"
    volumes:
      - ./fastapi:/code
  nextjs:
    build: ./nextjs
    network_mode: "host"
    volumes:
      - ./nextjs:/app
      - nodemodules:/app/node_modules

volumes:
  nodemodules: {}