name: 'Publish fastapi-nextauth-jwt to pypi'

on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: run pytest
        run: |
          pytest

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup flit
        run: python3 -m pip install flit

      - name: Build package
        run: flit build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
